---
db:
  dsn: DBI:mysql:database=sabredav;host=localhost
  user: cortex
  password: Abakus42
  options:
    RaiseError: 1
    AutoCommit: 0
  #addressbook table name
  tbl_addressbooks: addressbooks
  # cards table name
  tbl_cards: cards

files:
  create_folders: yes
  delete_data_dir_before_create: 1
  # data_dir - withouth ending slash
  data_dir: data
  # params for File::Path make_path and remove_tree
  path_options:
    verbose: 1
